### ISSUE TITLE
[BUG] Errors on delete-relation

### ISSUE THREAD

**Issue by mmanciop** [balbirthomas/mongodb-operator#1]
```
unit-mongodb-k8s-0: 15:42:35 ERROR unit.mongodb-k8s/0.juju-log database:1: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 331, in <module>
    main(MongoDBCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 406, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/src/mongoprovider.py", line 110, in _on_database_relation_broken
    databases = json.loads(event.relation.data[self.charm.app]['databases'])
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/model.py", line 400, in __getitem__
    return self._data[key]
KeyError: 'databases'
unit-mongodb-k8s-0: 15:42:36 ERROR juju.worker.uniter.operation hook "database-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by balbirthomas** [comment]
Should be fixed in https://github.com/balbirthomas/mongodb-operator/commit/a7b7554cd8fbe375d2b931e61981d874e458c2e8
