### ISSUE TITLE
Very spurious debug logs

### ISSUE THREAD

**Issue by mmanciop** [balbirthomas/mongodb-operator#2]
Below there is a brief excerpt from a `juju debug-log` for `juju deploy ./mongodb-k8s` built from the tip of `pebble-migration` (95e8071cbae5ae18e474f089d438ca1f27ec29eb). The spam is really noisy and makes `juju debug-log` almost impossible to use in complex models. Also, there is no indication whether these errors are transient (and therefore, AT BEST, should be a debug) or something more serious, which should affect the status of the charm:

```
unit-mongodb-k8s-0: 15:56:03 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-mongodb-k8s-0: 15:56:03 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-mongodb-k8s-0: 15:56:05 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:10 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:15 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:20 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:22 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-mongodb-k8s-0: 15:56:22 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-mongodb-k8s-0: 15:56:25 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:30 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:35 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:40 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:44 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-mongodb-k8s-0: 15:56:44 ERROR unit.mongodb-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/pebble.py", line 58, in connect
    self.sock.connect(self.socket_path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/pebble.py", line 737, in _request_raw
    response = self.opener.open(request, timeout=self.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/pebble.py", line 72, in http_open
    return self.do_open(_UnixSocketConnection, req, socket_path=self.socket_path)
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/charm.py", line 331, in <module>
    main(MongoDBCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 406, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 83, in _on_config_changed
    if not self.have_security_key(container):
  File "./src/charm.py", line 310, in have_security_key
    key_file = container.pull(file_path)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/model.py", line 1110, in pull
    return self._pebble.pull(path, encoding=encoding)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/pebble.py", line 925, in pull
    response = self._request_raw('GET', '/v1/files', query, headers)
  File "/var/lib/juju/agents/unit-mongodb-k8s-0/charm/venv/ops/pebble.py", line 750, in _request_raw
    raise ConnectionError(e.reason)
ops.pebble.ConnectionError: [Errno 2] No such file or directory
unit-mongodb-k8s-0: 15:56:44 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb-k8s-0: 15:56:44 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-mongodb-k8s-0: 15:56:45 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
unit-mongodb-k8s-0: 15:56:50 ERROR juju.worker.uniter pebble poll failed for container "mongodb": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/mongodb/pebble.socket: connect: no such file or directory
```

**Comment by balbirthomas** [comment]
This is indeed a bug the charm should be trapping ConnectionError. Will fix.

**Comment by balbirthomas** [comment]
Should be fixed in https://github.com/balbirthomas/mongodb-operator/commit/8b4b22243971b236e771b0c330ac704afb28a694
